package com.example.employeemanagementsystem.service;

import com.example.employeemanagementsystem.domain.Employee;
import com.example.employeemanagementsystem.repository.EmployeeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Objects;

@Service // This means that this class is a service
public class EmployeeService {
    @Autowired
    /*
      To get the bean which is auto-generated by Spring
      We will use it to handle the data.
    */
    EmployeeRepository employeeRepository;

    // Gets all employees
    public List<Employee> getAllEmployees()
    {
        // finds and returns all employee data
        return employeeRepository.findAll();
    }

    // Save an employee
    public void saveEmployee(Employee emp)
    {
        // saves employee data to database
        employeeRepository.save(emp);
    }

    // get employee by id
    public Employee getEmployeeById(Long id)
    {
        // finds employee by id
        Employee emp = employeeRepository.getReferenceById(id);

        // if there is not an employee who has the id, throw the exception
        if (Objects.isNull(emp))
        {
            throw new RuntimeException("Employee not found.");
        }
        return emp;
    }

    // delete employee by id
    public String deleteEmployeeById(Long id)
    {
        // find an employee by id
        Employee emp = employeeRepository.getReferenceById(id);

        // if no employee with id exists, throw the exception
        if (Objects.isNull(emp))
        {
            throw new RuntimeException("Employee not found");
        }

        // delete the employee with matching id from the database
        employeeRepository.deleteById(id);

        return "Deleted: " + emp.getFirstName() + " " + emp.getLastName();
    }
}
